import localfont from "next/font/local"
import "./globals.css";

const founder = localfont({
  src: [
    {
      path: "../../public/FoundersGrotesk-Semibold.ttf",
    }
  ],
  variable: "--font-founder",
});

const montreal = localfont({
  src: [
    {
      path: "../../public/NeueMontreal-Regular.ttf",
    }
  ],
  variable: "--font-montreal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${founder.variable} ${montreal.variable}`}>
      <body>{children}</body>
    </html>
  );
}
